name: The PHP League Style Checks

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    name: The PHP League Style Checks
    steps:

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Download dependencies
        uses: ramsey/composer-install@v3

      - name: Check Coding Style
        run: composer lint
